app:
   build: .
   command: nodemon --watch server --watch database/* --watch crawl --watch automatedAnnotation --watch expressionDomain --watch client/index.html --watch oracles --watch compose-dev.yml server/index.js
   links:
      - db
      - elasticanalysis
   ports:
      - 3333:3333
   environment:
      - POSTGRES_PASSWORD=password
      - NODE_ENV=development
   volumes: 
      - .:/usr/mywi
   tty: true
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=password
   ports:
      - 5432:5432
   volumes:
      - /etc/postgresql
      - /var/log/postgresql
      - /var/lib/postgresql
      - /var/lib/postgresql/data
   log_driver: "none"
elasticanalysis: 
   image: elasticsearch:1.7
   environment:
      - ELASTICSEARCH_USER=user
      - ELASTICSEARCH_PASS=password
   expose:
      - 9200
