app:
   build: .
   command: nodemon --watch server --watch database --watch postgresDB --watch crawl --watch automatedAnnotation --watch expressionDomain server/index.js
   links:
      - db
      - elasticanalysis
   ports:
      - 3333:3333
   environment:
      - POSTGRES_PASSWORD=password
      - NODE_ENV=development
   volumes: 
      - .:/usr/mywi
   tty: true
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=password
   ports:
      - 5432:5432
   volumes:
      - ./_storage/etc:/etc/postgresql
      - ./_storage/log:/var/log/postgresql
      - ./_storage/data:/var/lib/postgresql
      - ./_storage/data/data:/var/lib/postgresql/data
elasticanalysis: 
   image: elasticsearch:1.7
   environment:
      - ELASTICSEARCH_USER=user
      - ELASTICSEARCH_PASS=password
   expose:
      - 9200