app:
   build: .
   command: node server/index.js
   links:
      - db
   ports:
      - 4444:3333
   environment:
      - POSTGRES_PASSWORD=password
      - NODE_ENV=experimental
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=password
   ports:
      - 5432:5432
elasticanalysis: 
   image: elasticsearch:1.7
   environment:
      - ELASTICSEARCH_USER=user
      - ELASTICSEARCH_PASS=password
   expose:
      - 9200